apiVersion: v2
name: grafana-koshee
description: Koshee-branded Grafana deployment
type: application
version: 1.0.0
appVersion: "12.2.0"
dependencies:
  - name: grafana
    version: "8.8.2"
    repository: https://grafana.github.io/helm-charts
